### PR TITLE
Removed iOS 6 Support, update Error & Success (Added Image), A bit of code clean-up

### PR DESCRIPTION
**Pull request by KevinvdBurg**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

- Removed iOS6 support
- Moved Helper methods & Enums to it's own folder/file
- Added `ShowInfoWithStatus`
- Added outline versions for `Success`, `Error` and `Info`
- All files now use the `BTProgressHUD` namespace
- ~~Removed the ImageView size (24 x 24) use the size you want~~ Increase the size to 32 * 32, but now it beter scales none square images

### :arrow_heading_down: What is the current behavior?
- iOS6 is still supported (Why)

### :new: What is the new behavior (if this is a feature change)?
-  Added `ShowInfoWithStatus`
- Updated icon's for `Success`, `Error` and `Info`
- Added ImageStyles for `Success`, `Error` and `Info` (Outline or Outline Full)

### :boom: Does this PR introduce a breaking change?
- Removed Support for the iOS6 style
- All files now use the `BTProgressHUD` namespace so the `BigTed` is no longer used

### :bug: Recommendations for testing
- Start the demo project and see if all links stil work (@Cheesebaron one note, I was unable to test the ~~`ShowSuccessWithStatus`, `ShowErrorWithStatus` and `ShowInfoWithStatus` because it couldn't load the images, can you explain this proces)~~ Convent it to Base64 Images

### :thinking: Checklist before submitting

- ✅  All projects build
- ✅  Follows style guide lines 
- ✅  Relevant documentation was updated
- ✅  Rebased onto current develop

### CODE REVIEW

**Comment by Cheesebaron** [comment]
Ah, the dreaded image issue. When you bundle images in a library, you need to tell where they can be found. This is what the `BTProgressHud.targets` file are for. If you moved stuff around, you might need to adjust the paths there too.

**Comment by KevinvdBurg** [comment]
Ah ok! I have a private nuget package and I solved it by using a Base64 string and converting that to an UIImage! 🎉 
No more issues with loading from files! 


Screenshot 2021-06-18 at 14 11 08

**Comment by KevinvdBurg** [comment]
@Cheesebaron if you want me to move all images to this Base64 format let me know, it wil make the whole image problem obsolete. Otherwise let me know I could test `ShowSuccessWithStatus`, `ShowErrorWithStatus` and `ShowInfoWithStatus`. I'm not comfortable merging this PR without seeing it in action beforehand. 🙈

**Comment by KevinvdBurg** [comment]
@Cheesebaron I convert the images to Base64 icons's and added the different  image styles. I'm not gonna add extra features to this PR.

Can you check if every thing is working at your end, if so the version could be upped to `1.4` because there are some breaking changes

**Comment by Cheesebaron** [comment]
@KevinvdBurg thanks. Will have a look asap.

Still not 100% sure about the base64 images are a good way to embed images.

**Comment by KevinvdBurg** [comment]
I 100% agree that it is not an ideal solution but it removes a lot of head-aces trying to embed images in an Xamarin Nuget package.

I would rather have a custom BTProgressHUB xcassets so the images could be a vector and have a darkmode counterpart. But I have yet to find a solution for this

**Comment by Cheesebaron** [comment]
I've just given it a spin. Not sure, but the masking doesn't seem to be working. Will investigate a bit.

**Pull request merged**
